baseURL = 'http://et12.edu.ar/'
languageCode = 'en-us'
title = 'ET12 D1'
[module]
[[module.imports]]
  path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  themeVariant = [ "auto", "red" , "relearn-light", "relearn-dark", "blue", "green"]

[[menu.shortcuts]]
name = "<i class='fab fa-brands fa-github'></i> GitHub repo"
identifier = "ds"
url = "https://github.com/et12webmaster/et12webmaster.github.io"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-brands fa-instagram'></i> Instagram"
url = "https://www.instagram.com/escuelatec12/"
weight = 11

[[menu.shortcuts]]
name = "<i class='fab fa-brands fa-facebook'></i> Facebook"
identifier = "hugodoc"
url = "https://www.facebook.com/jose.desanmartin.927"
target = "_blank"
weight = 20
